### ISSUE TITLE
Need to integrate monitoring into puppet automation

### ISSUE THREAD

**Issue by robertstarmer** [CiscoSystems/cisco-openstack-docs#11]
Assigned edgar in place of Rohit getting into the system.

**Comment by rohitagarwalla** [comment]
i can work with edgar on this one.

**Comment by robertstarmer** [comment]
Reasigning to Rohit.

**Comment by robertstarmer** [comment]
collectd puppet module is now available.  It may also be integrated into the packaged environment.  The git repository is here:

https://github.com/CiscoSystems/puppet-collectd.

**Comment by emagana-zz** [comment]
Code tested and working
