### ISSUE TITLE
need to add modules to openstack puppet deb package

### ISSUE THREAD

**Issue by robertstarmer** [CiscoSystems/cisco-openstack-docs#18]
need to add:

CiscoSystems/puppet-cobblerd
CiscoSystems/puppet-snmpd
saz/puppet-ssh

**Comment by robertstarmer** [comment]
puppetlabs/puppetlabs-rsync

**Comment by robertstarmer** [comment]
ghoneycutt/puppet-xinetd

**Comment by robertstarmer** [comment]
First one was supposed to be collected

**Comment by sorenisanerd** [comment]
Can you explain why we need these? I wonder most about xinetd.

**Comment by sorenisanerd** [comment]
Added these submodules

 modules/collectd
 modules/rsync
 modules/snmpd
 modules/ssh

Waiting for some input on the xinetd before I add that.

**Comment by robertstarmer** [comment]
These are all needed for the puppetlabs swift puppet deployment.

**Comment by robertstarmer** [comment]
Can you add the xinetd module? Or do you need more info?

**Comment by robertstarmer** [comment]
So, I did try to remove the xinetd requirement, and the code looks like you should be able to remove it (in swift/manifests/server.pp there is a call to rsync::server, which passes use_xinetd as true).  rsync::server also sets use_xinetd as true in the parameters.  xinetd is called as an include inside an if(use_xinetd) section, but even if this is false, the system fails with:

rror 400 on SERVER: Could not find class xinetd for swiftproxy01.cc.lab at /usr/share/puppet/modules/rsync/manifests/server.pp:19

**Comment by sorenisanerd** [comment]
I've added it to the packages now. Sorry about the delay.

**Comment by robertstarmer** [comment]
NP!

There will be more...
