### ISSUE TITLE
Enable Horizon "Cisco" skin via puppet module

### ISSUE THREAD

**Issue by robertstarmer** [CiscoSystems/cisco-openstack-docs#7]
Change out the Ubuntu skin for a Cisco skin when deploying using the Ubuntu packaged Horizon.

**Comment by sorenisanerd** [comment]
This happens automatically if you use my repository. It contains a new pakage, openstack-dashboard-cisco-theme, which gets installed automatically when openstack-dashboard is installed.

**Comment by robertstarmer** [comment]
Yes, I should have updated the issue. I have validated this as well. Works perfectly!
